services:
  postgres:
    image: postgres:17
    container_name: grocery-db

    environment:
      POSTGRES_USER: grocery
      POSTGRES_PASSWORD: grocery
      POSTGRES_DB: grocery

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
